name: 'DevSecOps Application Security Actions'
description: 'Running Fority Security Scans for project codes'

inputs:
  environment:
    required: true
  application_release_name:
    required: true
  release_version:
    required: false
  kube_config:
    required: false
    
  is_helm_deployment:
    required: false
  helm_chart_path:
    required: false
  helm_values_file:
    required: false
  helm_values_file_path:
    required: false
  image_name:
    required: false
  image_tag:
    required: false
  cluster_namespace:
    required: false
  create_namespace:
    required: false
  helm_argument: 
    required: false
  dry_run:
    required: false
    default: false
  is_atomic:
    required: false
    default: false
  deployment_script_path:
    required: false
  deployment_script_name:
    required: false
  release_strategy:
    required: false
    default: 'standard'
  enable_canary:
    required: false
  canary_weightage:
    required: false
  
    
  is_azure_webapp_deployment:
    required: false
  webapp_name:
    required: true
  resource_group:
    required: false
  source_path:
    required: false
  azure_profile:
    required: false
  azure_sp: 
    required: false
  azure_client_id: 
    required: false
  azure_client_secret: 
    required: false
  azure_tenant_id:
    required: false
  subscription:
    required: false
  slot_name:
    required: false
  configuration_file:
    required: false
  startup_command:
    required: false
    
runs:
  using: "composite"
  steps:
    - run: echo Hello, You are Executing Composite action to deploy your project
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash  
    - name: ========== Deploy project using helm ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CD/helm@v1.2.21
      if: ${{ inputs.is_helm_deployment == 'true' && inputs.release_strategy == 'standard'}}
      with:
        environment: ${{inputs.environment}}
        application_release_name: ${{inputs.application_release_name}}
        release_version: ${{inputs.release_version}}
        kube_config: ${{inputs.kube_config}}
        is_helm_deployment: ${{inputs.is_helm_deployment}}
        helm_chart_path: ${{inputs.helm_chart_path}}
        helm_values_file: ${{inputs.helm_values_file}}
        helm_values_file_path: ${{inputs.helm_values_file_path}}
        image_name: ${{inputs.image_name}}
        image_tag: ${{inputs.image_tag}}
        cluster_namespace: ${{inputs.cluster_namespace}}
        create_namespace: ${{inputs.create_namespace}}
        helm_argument: ${{inputs.helm_argument}}
        dry_run: ${{inputs.dry_run}}
        is_atomic: ${{inputs.is_atomic}}
        deployment_script_path: ${{inputs.deployment_script_path}}
        deployment_script_name: ${{inputs.deployment_script_name}}
        
    - name: ========== Deploy project using helm ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CD/helm_blue_green@v1.2.21
      if: ${{ inputs.is_helm_deployment == 'true' && inputs.release_strategy != 'standard'}}
      with:
        environment: ${{inputs.environment}}
        application_release_name: ${{inputs.application_release_name}}
        release_version: ${{inputs.release_version}}
        kube_config: ${{inputs.kube_config}}
        helm_chart_path: ${{inputs.helm_chart_path}}
        helm_values_file: ${{inputs.helm_values_file}}
        helm_values_file_path: ${{inputs.helm_values_file_path}}
        image_name: ${{inputs.image_name}}
        image_tag: ${{inputs.image_tag}}
        cluster_namespace: ${{inputs.cluster_namespace}}
        create_namespace: ${{inputs.create_namespace}}
        helm_argument: ${{inputs.helm_argument}}
        dry_run: ${{inputs.dry_run}}
        is_atomic: ${{inputs.is_atomic}}
        deployment_script_path: ${{inputs.deployment_script_path}}
        deployment_script_name: ${{inputs.deployment_script_name}}    
        release_strategy: ${{inputs.release_strategy}}  
        enable_canary: ${{inputs.enable_canary}}  
        canary_weightage: ${{inputs.canary_weightage}}  
        
    - name: ========== AZURE WEB APP Deployment ==========
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CD/azure-webapp@v1.2.21
      if: ${{ inputs.is_azure_webapp_deployment == 'true'}}
      with:
        environment: ${{inputs.environment}}
        application_release_name: ${{inputs.application_release_name}}
        release_version: ${{inputs.release_version}}
        source_path: ${{inputs.source_path}}
        image_name: ${{inputs.image_name}}
        image_tag: ${{inputs.image_tag}}
        webapp_name: ${{inputs.webapp_name}}
        resource_group: ${{inputs.resource_group}}
        azure_profile: ${{inputs.azure_profile}}
        azure_sp: ${{inputs.azure_sp}}
        azure_client_id: ${{inputs.azure_client_id}}
        azure_client_secret: ${{inputs.azure_client_secret}}
        azure_tenant_id: ${{inputs.azure_tenant_id}}
        subscription: ${{inputs.subscription}}
        slot_name: ${{inputs.slot_name}}
        configuration_file: ${{inputs.configuration_file}}
        startup_command: ${{inputs.startup_command}}
    
        
        
        
