ame: 'BMC Helix Integration & CR creation'
description: 'Deployment using helm charts'

inputs:

  helix_username:
    required: true
  helix_password:
    required: true
    
  remedy_url:
    required: false
    default: 'https://mnscorp-rod-qa-restapi.onbmc.com'
  template_id:
    required: false
    default: 'IDGDZNKNB42FKAR0JR4QRJ04VW5KAS'
    
  change_request_id:
    required: true 
  update_status:
    required: true
  update_reason:
    required: true
    default: 'updating CR'
  
runs:
  using: "composite"
  steps:
#     - name: Get BMC Remedy API token
#       id: bmcremedylogin
#       uses: fjogeleit/http-request-action@master
#       with:
#         url: "${{inputs.remedy_url}}/api/jwt/login"  
#         method: 'POST'
#         contentType: application/x-www-form-urlencoded     
#         data: '{"username": "${{inputs.bmc_username}}", "password": "${{ inputs.bmc_password }}"}'
     
#     - name: Assign API response and Manipulate Input Product name
#       run: |
#          echo "TOKEN=${{ steps.bmcremedylogin.outputs.response }}" >> $GITHUB_ENV
#       shell: bash

  - name: Get BMC Remedy API token
    id: bmcremedylogin
    uses: fjogeleit/http-request-action@master
    with:
      # url: 'https://mnscorp-rod-qa-restapi.onbmc.com/api/jwt/login'    
      url: "${{inputs.remedy_url}}/api/jwt/login"
      method: 'POST'
      contentType: application/x-www-form-urlencoded     
      data: '{"username": "${{inputs.bmc_username}}", "password": "${{ inputs.bmc_password }}"}'
      
  - name: Assign API response
    run: |
       echo "TOKEN=${{ steps.bmcremedylogin.outputs.response }}" >> $GITHUB_ENV
    shell: bash   
    
  - name: Get CR status 
    id: bmcremedycrstatus
    run: |
      curl -X GET "https://mnscorp-rod-qa-restapi.onbmc.com/api/arsys/v1/entry/CHG:ChangeInterface?q='Infrastructure%20Change%20ID'=\"${{ inputs.change_request_id }}\"&fields=values(Change%20Request%20Status)" \
      -H "Authorization: AR-JWT ${{ env.TOKEN }}" \
      -H "Content-Type: application/json" > $HOME/response.json
      cat $HOME/response.json
      echo "CR_STATUS=$(jq -r '.entries[0].values["Change Request Status"]' $HOME/response.json)" >> $GITHUB_ENV
    shell: bash    
    
  - name: Print CR status
    run: |
        echo "${{ env.CR_STATUS }}"
    shell: bash      

  - name: Update CR for Implementation in Progress
    uses: fjogeleit/http-request-action@master
    with:
      url: 'https://mnscorp.jitterbit.eu/mnscorp-dev-ca/gitHubAutoCr/updatecr'        
      method: 'POST'
      timeout: 80000
      username: ${{inputs.helix_username}}
      password: ${{ inputs.helix_password }}
      #All dates passed here will be dynamically parameterized, hence no need to get it from the Engineers
      data: >-
        {
          "change_request_id": "${{ inputs.change_request_id }}",
          "status": "${{ inputs.update_status }}",
          "status_reason": "${{ inputs.update_reason }}"
        }


     
