name: 'BMC Helix Integration & CR creation'
description: 'Deployment using helm charts'

inputs:
  action:
    required: true
    default: update
    
  portfolio:
    required: true
  start_date:
    description: 'Change Implementation Start Date (YYYY-MM-DDTHH:MM:SS)'
    required: true
  end_date:
    description: 'Change Implementation End Date (YYYY-MM-DDTHH:MM:SS)'
    required: true
  app_name:
    description: 'Application Name'
    required: true
  change_description:
    description: 'Change Description'
    required: true
  change_category:
    description: 'Change Category'
    required: true
  outage_required:
    description: 'Outage Required?'
    required: true
  product_four_wall:
    description: 'Product 4 Wall Change?'
    required: true
  business_impact:
    description: 'Business Impact'
    required: true
  risk_impact:
    description: 'Risk and Impact assessment agreement'
    required: true
  bmc_username:
    required: true
  bmc_password:
    required: true
  remedy_url:
    required: false
    default: 'https://mnscorp-rod-qa-restapi.onbmc.com'
    
  template_id:
    required: false
    default: 'IDGDZNKNB42FKAR0JR4QRJ04VW5KAS'
 
  change_request_id:
    required: false
  update_status:
    required: false
  update_reason:
    required: false
    default: 'updating CR'  
    
runs:
  using: "composite"
  steps:
    - name: Create new CR 
      id: create-cr
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CD/bmc-helix-cr/create-cr@branch-bmc-helix-action
      with:
        portfolio: ${{inputs.portfolio}}
        start_date: ${{inputs.start_date}}
        end_date: ${{inputs.end_date}}
        app_name: ${{inputs.app_name}}
        change_description: ${{inputs.change_description}}
        change_category: ${{inputs.change_category}}
        outage_required: ${{inputs.outage_required}}
        product_four_wall: ${{inputs.product_four_wall}}
        business_impact: ${{inputs.business_impact}}
        risk_impact: ${{inputs.risk_impact}}
        bmc_username: ${{inputs.bmc_username}}
        bmc_password: ${{inputs.bmc_password}}
        remedy_url: ${{inputs.remedy_url}}
        template_id: ${{inputs.template_id}}
      if: ${{ inputs.action == 'create' }}
      
     
    - name: Update CR 
      id: update-cr
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CD/bmc-helix-cr/update-cr@branch-bmc-helix-action
      with:
#         portfolio: ${{inputs.portfolio}}
#         start_date: ${{inputs.}}
#         end_date: ${{inputs.start_date}}
#         app_name: ${{inputs.app_name}}
#         change_description: ${{inputs.change_description}}
#         change_category: ${{inputs.change_category}}
#         outage_required: ${{inputs.outage_required}}
#         product_four_wall: ${{inputs.product_four_wall}}
#         business_impact: ${{inputs.business_impact}}
#         risk_impact: ${{inputs.risk_impact}}
        bmc_username: ${{inputs.bmc_username}}
        bmc_password: ${{inputs.bmc_password}}
        remedy_url: ${{inputs.remedy_url}}
        template_id: ${{inputs.template_id}}
        change_request_id: ${{inputs.change_request_id}}
        update_status: ${{inputs.update_status}}
        update_reason: ${{inputs.update_reason}}
      if: ${{ inputs.action == 'update' }}
  
  
    
  
  
  
  
#     - name: Get BMC Remedy API token
#       id: bmcremedylogin
#       uses: fjogeleit/http-request-action@master
#       with:
#         url: "${{inputs.remedy_url}}/api/jwt/login"  
#         method: 'POST'
#         contentType: application/x-www-form-urlencoded     
#         data: '{"username": "${{inputs.bmc_username}}", "password": "${{ inputs.bmc_password }}"}'
     
     
     
     
#      - name: Update CR for Implementation in Progress
#         uses: fjogeleit/http-request-action@master
#         with:
#           url: 'https://mnscorp.jitterbit.eu/mnscorp-dev-ca/gitHubAutoCr/updatecr'        
#           method: 'POST'
#           timeout: 80000
#           username: ${{inputs.bmc_username}}
#           password: ${{ inputs.bmc_password }}
#           #All dates passed here will be dynamically parameterized, hence no need to get it from the Engineers
#           data: >-
#             {
#               "change_request_id": "${{ github.event.client_payload.change_request_id }}",
#               "status": "Implementation In Progress",
#               "status_reason": ""
#             }

#       - name: Release to Production
#         run: |
#           echo "Production Deployment successful"
#           sleep 10

#       - name: Update CR for Completed status
#         uses: fjogeleit/http-request-action@master
#         with:
#           url: 'https://mnscorp.jitterbit.eu/mnscorp-dev-ca/gitHubAutoCr/updatecr'        
#           method: 'POST'
#           timeout: 80000
#           username: github
#           password: ${{ secrets.BMC_HELIX_API_PASSWORD }}
#           #All dates passed here will be dynamically parameterized, hence no need to get it from the Engineers
#           data: >-
#             {
#               "change_request_id": "${{ github.event.client_payload.change_request_id }}",
#               "status": "Completed",
#               "status_reason": "Final Review Complete"
#             }

     
     
     

