name: 'Get Secrets from Azure key Vault'
description: 'Get Secrets from Azure key Vault'
inputs:
   
  sp_client_id:
    required: true
  sp_client_secret:
    required: true
  subscription_id:
    required: true
  tenent_id:
    required: true
  keyvault:
    required: true
  secret_keys:
    required: false


runs:
  using: "composite"
  steps:
    - run: ls -lart
      shell: bash

    - run : echo test $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash

    - uses: azure/CLI@v1
      id: GetAKVSecrets
      with:  
        azcliversion: 2.30.0
        inlineScript: |
            az login --service-principal -u ${{ inputs.sp_client_id }} -p ${{ inputs.sp_client_secret }} --tenant ${{ inputs.tenent_id }}
            az account set --subscription '${{ inputs.subscription_id }}'

            IFS=, read -ra values <<< "${{inputs.secret_keys}}"
            for v in "${values[@]}"
            do
              keyValue=''
              if az keyvault secret list --vault-name "${{inputs.keyvault}}" --query "[].name" | grep $v
              then
                  echo "Secret $v exists"

                  keyValue=$(az keyvault secret show --name "$v" --vault-name "${{inputs.keyvault}}" --query "value" -o tsv)

                  echo "::add-mask::${keyValue}"        
         
              else 
               echo "Secret $v Does not exist"
              fi

              echo "$v<<EOF" >> $GITHUB_ENV
              echo "$keyValue" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
    
            done

   
