# push_image.yml
name: 'Get Secrets from Azure key Vault'
description: 'Get Secrets from Azure key Vault'
inputs:
   
  sp_client_id:
    required: true
  sp_client_secret:
    required: true
  subscription_id:
    required: true
  tenent_id:
    required: true
  keyvault:
    required: true
  secret_keys:
    required: false


runs:
  using: "composite"
  steps:
    - run: ls -lart
      shell: bash
    - run : echo $RUNNER_NAME $RUNNER_OS $RUNNER_ARCH $RUNNER_TEMP
      shell: bash
      
        
########## Login and Push image to Azure Container Registry ##############

    - name: 'login to Azure'
      uses: azure/login@v1
      with:
        creds: '{"clientId": "${{ inputs.sp_client_id }}", "clientSecret": "${{ inputs.sp_client_secret }}", "subscriptionId": "${{ inputs.subscription_id }}", "tenantId": "${{ inputs.tenent_id }}"}'

# ########## Get info from key vault ##############    
    - uses: azure/CLI@v1
      id: GetAKVSecrets
      with:  
        azcliversion: 2.30.0
        inlineScript: |
            IFS=, read -ra values <<< "${{inputs.secret_keys}}"
            for v in "${values[@]}"
            do
              keyValue=$(az keyvault secret show --name "$v" --vault-name "${{inputs.keyvault}}" --query "value" -o tsv)
              echo "::add-mask::${keyValue}"
              echo "AKV_${v}=${keyValue}" >> $GITHUB_ENV
            done

            
