name: 'DevSecOps Application Security Actions'
description: 'Running Fority Security Scans for project codes'

inputs:
  
  environment:
    required: false
    default: dev    
  application_release_name:
    required: false
  release_version:
    required: false  
  webapp_name:
    required: false
  resource_group:
    required: false
  source_path:
    required: false
  image_name:
    required: false
  image_tag:
    required: false
    default: latest
  azure_profile:
    required: false
  azure_sp: 
    required: false
  azure_client_id: 
    required: false
  azure_client_secret: 
    required: false
  azure_tenant_id:
    required: false
  subscription:
    required: false
  slot_name:
    required: false
  configuration_file:
    required: false
  startup_command:
    required: false
  
runs:
  using: "composite"
  steps:
  
    - run: echo 'Deploy to Azure WebApp using Profile and Source path / Image'
      if: ${{ inputs.azure_profile != ''  }}
      shell: bash
      
    - name: retreive image info
      id: get_image_path
      run: |
        if [ -z ${{inputs.image_name}} ]; then
          image_path=''
        else
          image_path=${{inputs.image_name}}:${{inputs.image_tag}}
        fi
        echo "IMAGE=${image_path}" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: 'Deploy to Azure WebApp using Profile and Source'
      if: ${{ inputs.azure_profile != '' }}
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{inputs.webapp_name}}
        publish-profile: ${{ inputs.azure_profile }}
        package: ${{inputs.source_path}}
        images: ${{inputs.image_name}}:${{inputs.image_tag}}
        slot-name: ${{inputs.slot_name}}
        
    
#     - run: echo 'Deploy to Azure WebApp using Profile and Container Image'
#       if: ${{ inputs.azure_profile != '' && ( inputs.image_name != '' && inputs.source_path == '') }}
#       shell: bash
#     - name: 'Deploy to Azure WebApp using Profile and Container'
#       if: ${{ inputs.azure_profile != '' && ( inputs.image_name != '' && inputs.source_path == '') }}
#       uses: azure/webapps-deploy@v2
#       with: 
#         app-name: ${{inputs.webapp_name}}
#         publish-profile: ${{ inputs.azure_profile }}
#         image: ${{inputs.image_name}}:${{inputs.image_tag}}


    - run: echo 'Deploy to Azure Webapp using Service Principal and Credential '
      if:  ${{ inputs.azure_profile == '' }}
      shell: bash
      
    - name: 'Deploy to Azure Webapp using Service Principal - by login to Azure'
      uses: azure/login@v1.4.6
      with:
        creds: '{"clientId": "${{ inputs.azure_client_id }}", "clientSecret": "${{ inputs.azure_client_secret }}", "subscriptionId": "${{ inputs.subscription }}", "tenantId": "${{ inputs.azure_tenant_id }}"}'
      if:  ${{ inputs.azure_profile == '' }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{inputs.webapp_name}}
        images: ${{steps.get_image_path.outputs.IMAGE}}  #${{inputs.image_name}}:${{inputs.image_tag}}
        package: ${{inputs.source_path}}
        slot-name: ${{inputs.slot_name}}
      if:  ${{ inputs.azure_profile == ''  }}
      
      
      
      
      
#     - uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{inputs.webapp_name}}
#         package: ${{inputs.source_path}}
#         slot-name: ${{inputs.slot_name}}
#       if:  ${{ inputs.azure_profile == '' && inputs.image_name == '' }}  


#   - name: Deploy to Azure Web Apps
#     uses: azure/CLI@v1
#     id: webapp
#     with:
#         inlineScript: |
#           RETRY=5;
#           SLEEP=5;
#           COUNT=0;
#           CMD="az webapp deployment source config-zip \
#             --resource-group ${{ inputs.resource_group }} \
#             --name ${{ inputs.application_release_name }} \
#             --src ${{ inputs.source_path }} --timeout 360";
#           until [ "$COUNT" -ge $RETRY ]
#           do
#             $CMD && break;
#             COUNT=$((COUNT+1));
#             sleep $SLEEP;
#           done
#           if test $COUNT -eq $RETRY
#           then
#             echo "Deployment was unsuccesful :(";
#             exit 127;
#           fi
