name: GitHub Actions Version Updater

# Controls when the action will run.
# on: workflow_dispatch
on:
   schedule:
    # Automatically run on 15th of every month.
   - cron: '0 0 15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.ACTION_UPDATER }}
          
      - run: |
          ls -lart
          git --version
          git status
      
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.ACTION_UPDATER }}
          extra_workflow_locations: "./workflows"
