name: GitHub Actions Version Updater

# Controls when the action will run.
on: workflow_dispatch
  #schedule:
    # Automatically run on every Sunday
   # - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.ACTION_UPDATER }}
          
      - run: |
          ls -lart
          git --version
          git status
      
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@safe-dir
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.ACTION_UPDATER }}
          extra_workflow_locations: "./workflows"
